services:
  mysql:
    image: mysql:8.0
    container_name: banco_alimentos_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - banco_alimentos_data:/var/lib/mysql

volumes:
  banco_alimentos_data: