package com.group6.BancoAlimentos.Security.enums;

public enum Permits {
    EMPRESA_CREAR,
    EMPRESA_VER,
    EMPRESA_ACTUALIZAR,
    EMPRESA_ELIMINAR,

    DONACION_CREAR,
    DONACION_VER,
    DONACION_ACTUALIZAR,
    DONACION_ELIMINAR,

    PRODUCTO_CREAR,
    PRODUCTO_VER,
    PRODUCTO_ACTUALIZAR,
    PRODUCTO_ELIMINAR,

    ITEM_DONACION_CREAR,
    ITEM_DONACION_VER,
    ITEM_DONACION_ACTUALIZAR,
    ITEM_DONACION_ELIMINAR,

    INSTITUCION_CREAR,
    INSTITUCION_VER,
    INSTITUCION_ACTUALIZAR,
    INSTITUCION_ELIMINAR,

    ESTADO_PAGO_MODIFICAR,

    REMITO_CREAR,
    REMITO_VER,
    REMITO_ACTUALIZAR,
    REMITO_ELIMINAR,

    DETALLE_REMITO_CREAR,
    DETALLE_REMITO_VER,
    DETALLE_REMITO_ACTUALIZAR,
    DETALLE_REMITO_ELIMINAR,

    FACTURA_CREAR,
    FACTURA_VER,
    FACTURA_ACTUALIZAR,
    FACTURA_ELIMINAR,

    AUDITORIA_DONACION_VER,
    AUDITORIA_INSTITUCION_VER
}
