package com.group6.BancoAlimentos.Features.Producto.emun;


public enum Categoria {

    CEREALES_Y_DERIVADOS,
    LEGUMBRES,
    CONSERVAS,
    LACTEOS,
    CARNES_Y_PROTEINAS,
    FRUTAS_Y_VERDURAS,
    ACEITES_Y_GRASAS,
    AZUCARES_Y_DULCES,
    INFUSIONES_Y_BEBIDAS,
    CONDIMENTOS_Y_SALSAS,
    PANIFICADOS,
    ALIMENTOS_INFANTILES,
    ALIMENTOS_ESPECIALES,
    PRODUCTOS_DE_HIGIENE,
    PRODUCTOS_DE_LIMPIEZA,
    OTROS

}
